version: "3.7"
services:
  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - "3306:3306"
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  website:
    container_name: website
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
